spring:
  application:
    name: backend

  profiles:
    active: local

  cache:
    type: redis
    redis:
      time-to-live: 10m
      cache-null-values: false

logging:
  level:
    org.springframework.boot.context.config: DEBUG
    com.zaxxer.hikari: DEBUG

flowforge:
  rate-limit:
    workflow-execution:
      max-requests: 10
      window-seconds: 60

