server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5433}/flowforge
    username: flowforge
    password: flowforge

  jpa:
    open-in-view: false

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

  ai:

    openai:

      api-key: ${OPENAI_API_KEY:}

      chat:

        options:
          model: ${OPENAI_MODEL:gpt-4.1-mini}

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    com.flowforge: DEBUG

flowforge:
  security:
    jwt:
      secret: ${JWT_SECRET:change-this-development-secret-key-to-a-long-random-value}
      access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:900000}
      refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}
